services:
  webhook:
    image: registry.cn-hangzhou.aliyuncs.com/novacloud/wechat-webhook-new:ems1.1
    container_name: alertmanager-webhook
    ports:
      - "8999:8999"
    volumes:
      - ./logs:/var/log/wechat-webhook
    command:
      - /usr/bin/wechat-webhook
      - -wecom.key=6976d6f8-88db-4ee1-98eb-e238f581e378
      - -feishu.key=0a3f8d87-9fd3-4d14-a58d-25ff7dfd9ef5
      - -dingtalk.key=c46edefd4b38546527c7e21bb88e0b11a7f9cfa87d00c8e2162f6a82890fca2b
      - -addr=:8999
      - -log.dir=/var/log/wechat-webhook
      - -log.file=webhook.log
      